### ISSUE TITLE
Error: malformed path data

### ISSUE THREAD

**Issue by khusamov** [jkroso/parse-svg-path#4]
SVG path:

```
<path d="M5445.85 4213.32a2595.99 2595.99 0 100 5191.98 2595.99 2595.99 0 100-5191.98z"/>
```

Error:

```
(node:20528) UnhandledPromiseRejectionWarning: Error: malformed path data
    at C:\@repositories\svg-path-length\node_modules\parse-svg-path\index.js:45:42
    at String.replace (<anonymous>)
    at parse (C:\@repositories\svg-path-length\node_modules\parse-svg-path\index.js:29:7)


```

Still the same problem with arc:
```
M20087.17 6439.83c-166.45,-418.66 -251.94,-865.09 -251.94,-1315.61 0,-1966.61 1594.26,-3560.87 3560.87,-3560.87
```

Bug?

**Comment by rafaelaugustos** [comment]
Did you find a solution?

**Comment by khusamov** [comment]
It was a long time ago. See the comments in https://github.com/rveciana/svg-path-properties/issues/25
